### ISSUE TITLE
after merging one branch into another, all commits of the other branch are applied to the new one

### ISSUE THREAD

**Issue by lennart-g** [datascience-mobi/project-03-group-01#13]
![image](https://user-images.githubusercontent.com/48185791/59851162-39face80-936c-11e9-8be3-071a4c914607.png)
everything below the marked line are commits to other branches merged to the current one, making the commit count unrealistically large, and those commits also appear in pull requests. is this intended?

**Comment by npeschke** [comment]
Short answer: Yes.
Long answer: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
There is also an alternative to merging called rebasing if you are super interested:
https://git-scm.com/book/en/v2/Git-Branching-Rebasing
