### ISSUE TITLE
Loading gzipped dataset

### ISSUE THREAD

**Issue by npeschke** [datascience-mobi/project-03-group-01#4]
https://github.com/datascience-mobi/project-03-group-01/blob/b16af553963d679a147d297a0c8ffeaf23b62a5d/src/main.py#L7

Maybe add code to load the gzipped files directly as they are in the repository.

**Comment by lennart-g** [comment]
https://github.com/datascience-mobi/project-03-group-01/blob/74abbb7078df931f2876b19f3d161b480afd7f3c/src/load_image_vectors.py#L5
Done.
