### ISSUE TITLE
inverse_transformation does not work as it's supposed to

### ISSUE THREAD

**Issue by lennart-g** [datascience-mobi/project-03-group-01#8]
working code is pushed to the pca branch, can be executed via main.py. Produced images are either a black image with the black digit and some random white pixels around it or a dark grey background and a light grey digit, increasingly hard to distinguish the lower the variance for the pca.

the reconstructed images should probably look like [these](https://github.com/mGalarnyk/Python_Tutorials/blob/master/Sklearn/PCA/PCA_Image_Reconstruction_and_such.ipynb). If there is no mistake in our code we could still optimize the images with a thresholding method to yield a more significant difference between digit and background.

**Comment by npeschke** [comment]
Try to have a look at the data that you are plotting. In the PyCharm debugger, you can set watches for example to see the changes of a particular variable over the course of an algorithm.
![grafik](https://user-images.githubusercontent.com/37580463/59567774-521fd480-9072-11e9-8b10-b5b25dadede3.png)
You can also view these variables as an array with the button on the right hand side. Check this to see what kind of data you are actually plotting.

**Comment by lennart-g** [comment]
I changed the code so the image created by inverse_transform now only contains integer intensity values and is passed as list and not numpy array to the draw function ... Does not change the result, I guess the problem is somewhere in the sklearn pca part. While debugging I could not find a difference between an mnist image and an inverse-pca-image except obviously that the values are different

**Comment by npeschke** [comment]
Maybe have a closer look at the values themselves. What transformations are you applying to the pixel values?

Hint: What is done in `image_operations.draw(X_projected[0])`?

**Comment by lennart-g** [comment]
The function takes a 1D integer List, converts it to a 1D numpy array (the return type hint -> List[int] is wrong, how do i best write that for a numpy array?), converts that to a 28×28 2D numpy array and plots it. 

Just noticed that the drawn image will look like the right one on the second image (lots of black and a few white pixels) when numpy.interp gets a numpy array as parameter and no list but that won't fix it

**Comment by npeschke** [comment]
Have you tried to inverse transform the `test_pca` object in `reduce_dimensions` using the `pca` object with subsequent `scaler.inverse_transform`?

For me, this yields the desired outcome.
