### ISSUE TITLE
Can not invert pca in seperate function

### ISSUE THREAD

**Issue by lennart-g** [datascience-mobi/project-03-group-01#9]
code pushed to PCA branch, function to call is increase_dimensions in pca.py. To do so, comment out everything inside of the main block in main.py and de-comment the lines specified in pca.py above the function definition.

the difference to the reduce_dimensions function is that this one takes a reduced image list as parameter and does not create it on its own.

the obvious problem is: the inverse_transformation call won't create a 784 dimensional vector out of the reduced one (where should it know that numer - 784 - from anyway?).

**Comment by npeschke** [comment]
I cannot tell what you want to achieve with this function without a docstring or supporting comments.

**Comment by lennart-g** [comment]
solved, I was just missing some initialization steps. #8 remains open though
